### ISSUE TITLE
Report index file is (almost) not styled

### ISSUE THREAD

**Issue by mricaud** [xspec/xspec-maven-plugin-1#50] opened 2020-04-29 19:21 UTC
The XSpec reports index (`target\xspec-reports\index.html`) has poor style comparing to each html report (`target\xspec-reports\test-name.xspec\test-name.html`)
It used to be styled in version 1.5.1:
![image](https://user-images.githubusercontent.com/6360878/80637005-9a639d80-8a5e-11ea-8cb5-6e9078b43664.png)

Might be a good thing to align styling in reports as it was in 1.5.1 ?

**Comment by cmarchand** [comment] 2020-04-29 20:50
Duplicate of #49 .
Solved and published in 2.0.0

**Closed by cmarchand** 2020-04-29 20:50 UTC
Labels: duplicate
